import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {GetServerSideProps, InferGetServerSidePropsType} from 'next'
import DateGroup from '../types/DateGroup'
import DateContainer from '../components/DateContainer'

export default function Home({records}: { records: DateGroup[] }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.container}>
                {records.map(e => <DateContainer group={e} key={e.date}/>)}
            </div>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
    //测试用的假数据
    const records: DateGroup[] = [
        {
            date: '2021/9/2',
            messages: [
                {
                    id: '111-1',
                    senderId: 1980853671,
                    username: 'aaa',
                    messages: [
                        {content: '测试', time: '9:32', id: 'a'},
                        {content: '测试', time: '9:32', id: 's'},
                        {content: '测试', time: '9:32', id: 'd'},
                    ],
                },
                {
                    id: '111-2',
                    senderId: 1793675651,
                    username: 'bbb',
                    messages: [
                        {content: '测试', time: '9:32', id: 'f'},
                    ],
                },
            ],
        },
    ]

    return {
        props: {
            records,
        },
    }
}
