import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {GetServerSideProps} from 'next'
import DateContainer from '../components/DateContainer'
import getHistory, {ErrorRet, OkRet} from '../utils/getHistory'
import Error from 'next/error'

export default function Home({data, code}: { data: ErrorRet | OkRet, code?: number }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>聊天记录</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            {data.error ?
                <Error statusCode={code ?? 500} title={data.data}/> :
                <div className={styles.container}>
                    {data.data.map(e => <DateContainer group={e} key={e.date}/>)}
                </div>
            }
        </div>
    )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
    if (!context.query.res) {
        context.res.statusCode = 400
        return {
            props: {
                data: {
                    error: true,
                    data: 'Bad request',
                },
                code: 400,
            },
        }
    }

    const data = await getHistory(context.query.res as string)

    if (data.error)
        context.res.statusCode = 500

    return {
        props: {
            data,
        },
    }
}
